### PR TITLE
Add changelog

### PR DESCRIPTION
**Pull request by mjwilson-google**
Add a changelog, so we can publish an updated working draft.

Please take a look.

### CODE REVIEW

**Review by hoch — APPROVED** [review]
LGTM

**Comment by hoch** [comment]
Adding @svgeesus for visibility.

**Comment by svgeesus** [comment]
What does `<rs-changelog from="f7632e65a5708b01fcb78ca04e254e00b5864465">` expand to? A list of commit messages? A diff?

**Comment by svgeesus** [comment]
Also, once the document is published, will that changelog be static and not include changes after that publication? Because typically you would start a new section **Changes since Working Draft xx Nov 2023**

**Comment by hoch** [comment]
@svgeesus `rs-changelog` is explained here: https://github.com/w3c/respec/wiki/rs-changelog

@mjwilson-google Can you grab a screenshot of the rendered page?

**Comment by mjwilson-google** [comment]
> What does `<rs-changelog from="f7632e65a5708b01fcb78ca04e254e00b5864465">` expand to? A list of commit messages? A diff?

It expands to a list of commit messsages which link to diffs.  It's not the most user-friendly because some of the commit messsages are not very descriptive, but it's probably the fastest way to get an accurate list of everything that changed.  For the from field, I manually searched  and verified the first commit that landed after the last Working Draft was published.

> Also, once the document is published, will that changelog be static and not include changes after that publication? 

I believe so.  I've never published a Respec document before, but my understanding is when we run the export step a fully static version of the page is generated and that's what we will upload as the new working draft.

> Because typically you would start a new section **Changes since Working Draft xx Nov 2023**

Yes, although I'm a bit concerned that the changelog section will get very long if we do this.  Can we just keep the changes since the previous version in the changelog, and people can go back to previous versions to check those changes?

Here is a screenshot of part of the list; we have eight years of changes so it didn't all fit on one screen: 
image

**Comment by svgeesus** [comment]
> Yes, although I'm a bit concerned that the changelog section will get very long if we do this. Can we just keep the changes since the previous version in the changelog, and people can go back to previous versions to check those changes?

Sure, that works.

**Pull request merged**
