### PR TITLE
Add Feature Policy integration for WebMidi

### PR DESCRIPTION
**Pull request by raymeskhoury**

### CODE REVIEW

**Comment by raymeskhoury** [comment]
@cwilso @toyoshim ptal :)

**Comment by toyoshim** [comment]
LGTM

**Comment by toyoshim** [comment]
Shall we say that it causes a "SecurityError"  in the requestMIDIAccess's algorithm, step 11?
In current specs even with this change, it's still unclear what happens if the feature is disabled by the policy.

**Comment by raymeskhoury** [comment]
Updated, ptal

**Comment by toyoshim** [comment]
Thanks! LGTM again.

**Comment by raymeskhoury** [comment]
Thanks - I have no write access to the repo - so if this should be merged, please merge this :)

**Pull request merged**
